### PR TITLE
Node Deletion & Level Order Traversal of Binary Tree

### PR DESCRIPTION
**Pull request by BhaswatiRoy**
Fixes #

#### Changes proposed in this pull request:

-
-
-

#### Checklist

- [x] I have read the Contributing guidlines and Code of Conduct.
- [x] My branch is up-to-date.
- [x] Changes made by me are not breaking the code.
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by itisaby** [comment]
Looks good to me but it's already there in the repo, try to add some other algo that is not present in the repo

**Comment by BhaswatiRoy** [comment]
image

**Comment by BhaswatiRoy** [comment]
done @itisaby @shubho5das !

**Comment by BhaswatiRoy** [comment]
> cool @BhaswatiRoy good work

Thank you!

**Pull request merged**
